# Generated by Django 5.1.3 on 2024-12-04 05:09

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_recived', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['json_recived'], name='server_logg_json_re_cea1f3_gin')],
            },
        ),
    ]
